### ISSUE TITLE
Disable buttons if the user is not logged in

### ISSUE THREAD

**Issue by gjdanis** [ben-e-whitney/the-points-chart#5]
Without being logged in, clicking the buttons at the top and side of the screen brings the user back to the login dialog, and the page is refreshed even though there are no changes to the content. I would recommend disabling the buttons, unless the user is logged in.

**Comment by ben-e-whitney** [comment]
This is resolved in commit afd3ae05115081aea1dfcb6d93c462b5da711077.

**Comment by gjdanis** [comment]
Nice job...can you give me an account to play around with?

On Sat, Mar 14, 2015 at 1:31 AM, ben-e-whitney notifications@github.com
wrote:

> This is resolved in commit afd3ae0
> https://github.com/ben-e-whitney/the-points-chart/commit/afd3ae05115081aea1dfcb6d93c462b5da711077
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ben-e-whitney/the-points-chart/issues/5#issuecomment-79926251
> .

## 

GJD

**Comment by ben-e-whitney** [comment]
I'll email you.
